apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "retail-app.fullname" . }}-config
  namespace: {{ .Values.namespace }}
data:
  APP_ENV: "{{ .Values.env.APP_ENV }}"
  LOG_LEVEL: "{{ .Values.env.LOG_LEVEL }}"
