apiVersion: v1
kind: Secret
metadata:
  name: {{ include "retail-app.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_USER: "{{ .Values.secret.DB_USER }}"
  DB_PASSWORD: "{{ .Values.secret.DB_PASSWORD }}"
