apiVersion: v1
kind: Service
metadata:
  name: {{ include "retail-app.fullname" . }}-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "retail-app.name" . }}
spec:
  selector:
    app: {{ include "retail-app.name" . }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
